region_mapping = {
    "11": "Cao Bằng",
    "12": "Lạng Sơn",
    "14": "Quảng Ninh",
    "15": "Hải Phòng ",
    "16": "Hải Phòng",
    "17": "Thái Bình",
    "18": "Nam Định",
    "19": "Phú Thọ",
    "20": "Thái Nguyên",
    "21": "Yên Bái",
    "22": "Tuyên Quang",
    "23": "Hà Giang",
    "24": "Lao Cai",
    "25": "Lai Châu",
    "26": "Sơn La",
    "27": "Điện Biên",
    "28": "Hoà Bình",
    "29": "Hà Nội",
    "30": "Hà Nội",
    "31": "Hà Nội",
    "32": "Hà Nội",
    "33": "Hà Nội",
    "34": "Hải Dương",
    "35": "Ninh Bình",
    "36": "Thanh Hóa",
    "37": "Nghệ An",
    "38": "Hà Tĩnh",
    "43": "Đà Nẵng",
    "47": "ĐắkLak",
    "48": "Đắc Nông",
    "49": "Lâm Đồng",
    "50": "TPHCM",
    "51": "TPHCM",
    "52": "TPHCM",
    "53": "TPHCM",
    "54": "TPHCM",
    "55": "TPHCM",
    "56": "TPHCM",
    "57": "TPHCM",
    "58": "TPHCM",
    "59": "TPHCM",
    "60": "Đồng Nai",
    "61": "Bình Dương",
    "62": "Long An",
    "63": "Tiền Giang",
    "64": "Vĩnh Long",
    "65": "Cần Thơ",
    "66": "Đồng Tháp",
    "67": "An Giang",
    "68": "Kiên Giang",
    "69": "Cà Mau",
    "70": "Tây Ninh",
    "71": "Bến Tre",
    "72": "Vũng Tàu",
    "73": "Quảng Bình",
    "74": "Quảng Trị",
    "75": "Huế",
    "76": "Quảng Ngãi",
    "77": "Bình Định",
    "78": "Phú Yên",
    "79": "Nha Trang",
    "81": "Gia Lai",
    "82": "Kon Tum",
    "83": "Sóc Trăng",
    "84": "Trà Vinh",
    "85": "Ninh Thuận",
    "86": "Bình Thuận",
    "88": "Vĩnh Phúc",
    "89": "Hưng Yên",
    "90": "Hà Nam",
    "92": "Quảng Nam",
    "93": "Bình Phước",
    "94": "Bạc Liêu",
    "95": "Hậu Giang",
    "97": "Bắc Cạn",
    "98": "Bắc Giang",
    "99": "Bắc Ninh",
}

region_mapping_no_accents = {
    "11": "Cao Bang",
    "12": "Lang Son",
    "14": "Quang Ninh",
    "15": "Hai Phong ",
    "16": "Hai Phong",
    "17": "Thai Binh",
    "18": "Nam Dinh",
    "19": "Phu Tho",
    "20": "Thai Nguyen",
    "21": "Yen Bai",
    "22": "Tuyen Quang",
    "23": "Ha Giang",
    "24": "Lao Cai",
    "25": "Lai Chau",
    "26": "Son La",
    "27": "Dien Bien",
    "28": "Hoa Binh",
    "29": "Ha Noi",
    "30": "Ha Noi",
    "31": "Ha Noi",
    "32": "Ha Noi",
    "33": "Ha Noi",
    "34": "Hai Duong",
    "35": "Ninh Binh",
    "36": "Thanh Hoa",
    "37": "Nghe An",
    "38": "Ha Tinh",
    "43": "Da Nang",
    "47": "DakLak",
    "48": "Dac Nong",
    "49": "Lam Dong",
    "50": "TPHCM",
    "51": "TPHCM",
    "52": "TPHCM",
    "53": "TPHCM",
    "54": "TPHCM",
    "55": "TPHCM",
    "56": "TPHCM",
    "57": "TPHCM",
    "58": "TPHCM",
    "59": "TPHCM",
    "60": "Dong Nai",
    "61": "Binh Duong",
    "62": "Long An",
    "63": "Tien Giang",
    "64": "Vinh Long",
    "65": "Can Tho",
    "66": "Dong Thap",
    "67": "An Giang",
    "68": "Kien Giang",
    "69": "Ca Mau",
    "70": "Tay Ninh",
    "71": "Ben Tre",
    "72": "Vung Tau",
    "73": "Quang Binh",
    "74": "Quang Tri",
    "75": "Hue",
    "76": "Quang Ngai",
    "77": "Binh Dinh",
    "78": "Phu Yen",
    "79": "Nha Trang",
    "81": "Gia Lai",
    "82": "Kon Tum",
    "83": "Soc Trang",
    "84": "Tra Vinh",
    "85": "Ninh Thuan",
    "86": "Binh Thuan",
    "88": "Vinh Phuc",
    "89": "Hung Yen",
    "90": "Ha Nam",
    "92": "Quang Nam",
    "93": "Binh Phuoc",
    "94": "Bac Lieu",
    "95": "Hau Giang",
    "97": "Bac Can",
    "98": "Bac Giang",
    "99": "Bac Ninh",
}
